name: PHP Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        dependency-versions:
          - "lowest"
          - "highest"

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v2
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: "ramsey/composer-install@v3"
      with:
        dependency-versions: ${{ matrix.dependency-versions }}

    - name: PHPUnit tests
      uses: php-actions/phpunit@v2
      with:
        configuration: phpunit.xml
        php_version: ${{ matrix.php-version }}
        version: 9

    - name: Run PHPStan
      run: vendor/bin/phpstan
