name: PHP Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        dependency-versions:
          - "lowest"
          - "highest"

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: ${{ matrix.php-version }}

    - name: Install dependencies
      uses: "ramsey/composer-install@v3"
      with:
        dependency-versions: ${{ matrix.dependency-versions }}

    - name: PHPUnit tests
      uses: php-actions/phpunit@v4
      with:
        configuration: phpunit.xml
        php_version: ${{ matrix.php-version }}

    - name: Run PHPStan
      run: vendor/bin/phpstan
